import { Component, OnInit } from '@angular/core';
import { Usuario } from "../_models/usuario";
@Component({
  selector: 'app-usuarios',
  templateUrl: './usuarios.component.html',
  styleUrls: ['./usuarios.component.scss']
})
export class UsuariosComponent implements OnInit {

  usuarios:Usuario[] = [
    {
        id: 1,
        nome: 'Ataúlfo Bezerra',
        email: 'ataulfo@acasamax.com.br',
        acessoApp: true,
        acessoWeb: false,
        ativo: true,
    },
    {
      id: 2,
      nome: 'Luiz Brasão',
      email: 'luiz@acasamax.com.br',
      acessoApp: true,
      acessoWeb: true,
      ativo: true,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'Usuário Inativo da Silva',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    },
    {
      id: 3,
      nome: 'ÚLTIMO',
      email: 'inativo.dasilva@acasamax.com.br',
      acessoApp: true,
      acessoWeb: false,
      ativo: false,
    }
  ];

  constructor() { }

  ngOnInit() {
  }

}
