import { NgModule } from '@angular/core';
import {
	MatButtonModule,
	MatCheckboxModule,
	MatRadioModule,
	MatInputModule,
	MatFormFieldModule,
	MatToolbarModule,
	MatSidenavModule,
	MatIconModule,
	MatListModule,
	MatMenuModule,
	MatTooltipModule,
	MatSnackBarModule,
	MatSelectModule,
	MatDatepickerModule,
	MatNativeDateModule,
	MatSlideToggleModule,
	MatAutocompleteModule,
	MatProgressSpinnerModule
} from '@angular/material';

@NgModule({
	imports: [
		MatButtonModule,
		MatCheckboxModule,
		MatRadioModule,
		MatFormFieldModule,
		MatInputModule,
		MatToolbarModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatMenuModule,
		MatTooltipModule,
		MatSnackBarModule,
		MatSelectModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSlideToggleModule,
		MatAutocompleteModule,
		MatProgressSpinnerModule,
	],
	exports: [
		MatButtonModule,
		MatCheckboxModule,
		MatRadioModule,
		MatFormFieldModule,
		MatInputModule,
		MatToolbarModule,
		MatSidenavModule,
		MatIconModule,
		MatListModule,
		MatMenuModule,
		MatTooltipModule,
		MatSnackBarModule,
		MatSelectModule,
		MatDatepickerModule,
		MatNativeDateModule,
		MatSlideToggleModule,
		MatAutocompleteModule,
		MatProgressSpinnerModule
	],
	declarations: []
})
export class MaterialModule { }
